--------------------------------------------------------------------------------
-- Autocmds that likely will be placed in the .config/nvim folders
--
-- From TjDevries
--
-- :help event, au, createaucmd
--
-- Test with:
-- * :so %
-- * :au SmashThat
--
--
--------------------------------------------------------------------------------
-- local group = vim.api.nvim_create_augroup("SmashThat", { clear = true }) -- true ensures we don't have duplicate definitions
-- vim.api.nvim_create_autocmd(
--   "BufEnter",
--   pattern = { "Never" },
--   { command = "echo 'Hello 1'", group = group }
-- )
-- vim.api.nvim_create_autocmd("BufEnter", {
--   callback = function() end,
--   group = group,
--   buffer = 0,
-- })
